/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) foo_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[4] = {3, 1, 0, 0};
static const casadi_int casadi_s3[42] = {3, 10, 0, 3, 6, 9, 12, 15, 17, 20, 23, 26, 29, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* F:(i0[10])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6, a7, a8, a9;
  a0=26.;
  a1=3.5634615384615387e-001;
  a2=arg[0] ? arg[0][6] : 0;
  a1=(a1*a2);
  a1=(a0*a1);
  a3=-2.5506000000000000e+002;
  a4=5.5000000000000004e-001;
  a5=arg[0] ? arg[0][0] : 0;
  a6=sin(a5);
  a7=(a4*a6);
  a3=(a3*a7);
  a5=cos(a5);
  a4=(a4*a5);
  a7=-9.8100000000000005e+000;
  a8=arg[0] ? arg[0][9] : 0;
  a7=(a7*a8);
  a0=(a0*a7);
  a4=(a4*a0);
  a3=(a3+a4);
  a1=(a1+a3);
  a3=46.;
  a4=1.9626847826086954e-001;
  a0=arg[0] ? arg[0][7] : 0;
  a0=(a2+a0);
  a4=(a4*a0);
  a8=3.6499999999999999e-001;
  a9=arg[0] ? arg[0][2] : 0;
  a10=sin(a9);
  a11=(a5*a10);
  a9=cos(a9);
  a12=(a6*a9);
  a11=(a11+a12);
  a12=(a8*a11);
  a13=8.5299999999999998e-001;
  a14=(a13*a6);
  a15=(a2*a14);
  a16=arg[0] ? arg[0][1] : 0;
  a13=(a13*a5);
  a17=(a16*a13);
  a17=(a16*a17);
  a15=(a15+a17);
  a17=(a12*a15);
  a18=(a5*a9);
  a19=(a6*a10);
  a18=(a18-a19);
  a19=(a8*a18);
  a20=(a16*a14);
  a20=(a16*a20);
  a2=(a2*a13);
  a20=(a20-a2);
  a2=(a19*a20);
  a17=(a17-a2);
  a4=(a4+a17);
  a4=(a3*a4);
  a17=-4.5126000000000005e+002;
  a2=(a8*a11);
  a2=(a17*a2);
  a8=(a8*a18);
  a21=(a3*a7);
  a8=(a8*a21);
  a2=(a2+a8);
  a4=(a4+a2);
  a2=30.;
  a8=3.4999999999999998e-001;
  a22=arg[0] ? arg[0][8] : 0;
  a22=(a0+a22);
  a8=(a8*a22);
  a23=5.0000000000000000e-001;
  a24=(a5*a9);
  a25=(a6*a10);
  a24=(a24-a25);
  a25=arg[0] ? arg[0][4] : 0;
  a26=sin(a25);
  a24=(a24*a26);
  a25=cos(a25);
  a27=(a11*a25);
  a24=(a24+a27);
  a27=(a23*a24);
  a28=5.9999999999999998e-001;
  a11=(a28*a11);
  a29=(a0*a11);
  a29=(a15+a29);
  a30=arg[0] ? arg[0][3] : 0;
  a16=(a16+a30);
  a28=(a28*a18);
  a30=(a16*a28);
  a30=(a16*a30);
  a29=(a29+a30);
  a30=(a27*a29);
  a18=(a18*a25);
  a6=(a6*a9);
  a5=(a5*a10);
  a6=(a6+a5);
  a6=(a6*a26);
  a18=(a18-a6);
  a6=(a23*a18);
  a26=(a0*a28);
  a26=(a20-a26);
  a5=(a16*a11);
  a5=(a16*a5);
  a26=(a26+a5);
  a5=(a6*a26);
  a30=(a30-a5);
  a8=(a8+a30);
  a8=(a2*a8);
  a30=-2.9430000000000001e+002;
  a24=(a23*a24);
  a24=(a30*a24);
  a23=(a23*a18);
  a7=(a2*a7);
  a23=(a23*a7);
  a24=(a24+a23);
  a8=(a8+a24);
  a24=(a27*a22);
  a29=(a29+a24);
  a29=(a2*a29);
  a24=arg[0] ? arg[0][5] : 0;
  a24=(a16+a24);
  a23=(a24*a6);
  a23=(a24*a23);
  a23=(a2*a23);
  a29=(a29+a23);
  a29=(a29+a30);
  a11=(a11*a29);
  a6=(a6*a22);
  a26=(a26-a6);
  a26=(a2*a26);
  a27=(a24*a27);
  a24=(a24*a27);
  a2=(a2*a24);
  a26=(a26+a2);
  a26=(a26-a7);
  a28=(a28*a26);
  a11=(a11-a28);
  a11=(a8+a11);
  a4=(a4+a11);
  a11=(a12*a0);
  a15=(a15+a11);
  a15=(a3*a15);
  a11=(a16*a19);
  a11=(a16*a11);
  a11=(a3*a11);
  a15=(a15+a11);
  a15=(a15+a17);
  a15=(a15+a29);
  a14=(a14*a15);
  a19=(a19*a0);
  a20=(a20-a19);
  a20=(a3*a20);
  a12=(a16*a12);
  a16=(a16*a12);
  a3=(a3*a16);
  a20=(a20+a3);
  a20=(a20-a21);
  a20=(a20+a26);
  a13=(a13*a20);
  a14=(a14-a13);
  a14=(a4+a14);
  a1=(a1+a14);
  if (res[0]!=0) res[0][0]=a1;
  if (res[0]!=0) res[0][1]=a4;
  if (res[0]!=0) res[0][2]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* F_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jac_F:(i0[10],out_o0[3x1,0nz])->(jac[3x10,29nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[0] ? arg[0][0] : 0;
  a1=cos(a0);
  a2=8.5299999999999998e-001;
  a3=46.;
  a4=arg[0] ? arg[0][6] : 0;
  a5=sin(a0);
  a6=(a2*a5);
  a7=(a4*a6);
  a8=arg[0] ? arg[0][1] : 0;
  a9=cos(a0);
  a10=(a2*a9);
  a11=(a8*a10);
  a12=(a8*a11);
  a7=(a7+a12);
  a12=3.6499999999999999e-001;
  a13=arg[0] ? arg[0][2] : 0;
  a14=sin(a13);
  a15=(a9*a14);
  a16=cos(a13);
  a17=(a5*a16);
  a15=(a15+a17);
  a17=(a12*a15);
  a18=arg[0] ? arg[0][7] : 0;
  a18=(a4+a18);
  a19=(a17*a18);
  a19=(a7+a19);
  a19=(a3*a19);
  a20=arg[0] ? arg[0][3] : 0;
  a20=(a8+a20);
  a21=(a9*a16);
  a22=(a5*a14);
  a21=(a21-a22);
  a22=(a12*a21);
  a23=(a20*a22);
  a24=(a20*a23);
  a24=(a3*a24);
  a19=(a19+a24);
  a24=-4.5126000000000005e+002;
  a19=(a19+a24);
  a24=30.;
  a25=5.9999999999999998e-001;
  a26=(a25*a15);
  a27=(a18*a26);
  a27=(a7+a27);
  a28=(a25*a21);
  a29=(a20*a28);
  a30=(a20*a29);
  a27=(a27+a30);
  a30=5.0000000000000000e-001;
  a31=(a9*a16);
  a32=(a5*a14);
  a31=(a31-a32);
  a32=arg[0] ? arg[0][4] : 0;
  a33=sin(a32);
  a34=(a31*a33);
  a35=cos(a32);
  a36=(a15*a35);
  a34=(a34+a36);
  a34=(a30*a34);
  a36=arg[0] ? arg[0][8] : 0;
  a36=(a18+a36);
  a37=(a34*a36);
  a37=(a27+a37);
  a37=(a24*a37);
  a38=arg[0] ? arg[0][5] : 0;
  a38=(a20+a38);
  a39=(a21*a35);
  a40=(a5*a16);
  a41=(a9*a14);
  a40=(a40+a41);
  a41=(a40*a33);
  a39=(a39-a41);
  a41=(a30*a39);
  a42=(a38*a41);
  a43=(a38*a42);
  a43=(a24*a43);
  a37=(a37+a43);
  a43=-2.9430000000000001e+002;
  a37=(a37+a43);
  a19=(a19+a37);
  a43=-30.;
  a44=(a43*a41);
  a45=(a10+a28);
  a46=(a24*a45);
  a44=(a44-a46);
  a47=(a3*a10);
  a48=(a44-a47);
  a49=-46.;
  a50=(a49*a22);
  a48=(a48+a50);
  a50=(a8*a48);
  a51=(a8*a50);
  a19=(a19+a51);
  a51=(a3*a6);
  a52=(a6+a26);
  a53=(a24*a52);
  a54=(a24*a34);
  a54=(a53+a54);
  a55=(a51+a54);
  a56=(a3*a17);
  a55=(a55+a56);
  a56=(a4*a55);
  a19=(a19+a56);
  a19=(a2*a19);
  a56=-9.8100000000000005e+000;
  a57=arg[0] ? arg[0][9] : 0;
  a57=(a56*a57);
  a58=(a24*a57);
  a59=(a30*a58);
  a60=(a36*a46);
  a52=(a24*a52);
  a61=(a38*a52);
  a62=(a38*a61);
  a60=(a60+a62);
  a62=(a8*a6);
  a63=(a8*a62);
  a64=(a4*a10);
  a63=(a63-a64);
  a64=(a18*a28);
  a64=(a63-a64);
  a65=(a20*a26);
  a66=(a20*a65);
  a64=(a64+a66);
  a66=(a43*a64);
  a60=(a60+a66);
  a60=(a30*a60);
  a59=(a59+a60);
  a60=(a33*a59);
  a66=(a16*a60);
  a67=-1.4715000000000001e+002;
  a68=(a36*a53);
  a69=(a24*a45);
  a70=(a38*a69);
  a71=(a38*a70);
  a68=(a68-a71);
  a71=(a24*a27);
  a68=(a68+a71);
  a68=(a30*a68);
  a68=(a67+a68);
  a71=(a33*a68);
  a72=(a14*a71);
  a66=(a66+a72);
  a72=(a35*a59);
  a73=(a20*a54);
  a74=(a20*a73);
  a75=(a41*a36);
  a75=(a64-a75);
  a75=(a24*a75);
  a76=(a38*a34);
  a77=(a38*a76);
  a77=(a24*a77);
  a75=(a75+a77);
  a75=(a75-a58);
  a77=(a18*a44);
  a77=(a75+a77);
  a74=(a74-a77);
  a74=(a25*a74);
  a72=(a72+a74);
  a74=(a3*a57);
  a77=(a12*a74);
  a72=(a72+a77);
  a77=(a18*a47);
  a78=(a3*a6);
  a79=(a20*a78);
  a80=(a20*a79);
  a77=(a77+a80);
  a80=(a49*a63);
  a77=(a77+a80);
  a77=(a12*a77);
  a72=(a72+a77);
  a77=(a14*a72);
  a66=(a66+a77);
  a19=(a19-a66);
  a66=(a20*a44);
  a77=(a20*a66);
  a77=(a37+a77);
  a80=(a18*a54);
  a77=(a77+a80);
  a77=(a25*a77);
  a80=(a35*a68);
  a77=(a77+a80);
  a80=-1.6470990000000000e+002;
  a77=(a77+a80);
  a81=(a18*a51);
  a82=(a3*a10);
  a83=(a20*a82);
  a84=(a20*a83);
  a81=(a81-a84);
  a84=(a3*a7);
  a81=(a81+a84);
  a81=(a12*a81);
  a77=(a77+a81);
  a81=(a16*a77);
  a19=(a19+a81);
  a81=-1.4028300000000002e+002;
  a19=(a19+a81);
  a19=(a1*a19);
  a0=sin(a0);
  a81=(a16*a71);
  a84=(a14*a60);
  a81=(a81-a84);
  a84=(a16*a72);
  a81=(a81+a84);
  a84=(a8*a55);
  a85=(a8*a84);
  a86=(a22*a18);
  a86=(a63-a86);
  a86=(a3*a86);
  a87=(a20*a17);
  a88=(a20*a87);
  a88=(a3*a88);
  a86=(a86+a88);
  a86=(a86-a74);
  a86=(a86+a75);
  a88=(a4*a48);
  a86=(a86+a88);
  a85=(a85-a86);
  a85=(a2*a85);
  a81=(a81+a85);
  a85=(a14*a77);
  a81=(a81+a85);
  a85=5.5000000000000004e-001;
  a86=26.;
  a57=(a86*a57);
  a57=(a85*a57);
  a81=(a81+a57);
  a81=(a0*a81);
  a19=(a19-a81);
  if (res[0]!=0) res[0][0]=a19;
  a19=(a43*a41);
  a81=(a24*a28);
  a19=(a19-a81);
  a57=(a49*a22);
  a57=(a19+a57);
  a88=(a8*a57);
  a89=(a8*a88);
  a90=(a24*a26);
  a91=(a24*a34);
  a91=(a90+a91);
  a92=(a3*a17);
  a92=(a91+a92);
  a93=(a4*a92);
  a89=(a89+a93);
  a89=(a2*a89);
  a93=(a30*a58);
  a94=(a36*a81);
  a95=(a24*a26);
  a96=(a38*a95);
  a97=(a38*a96);
  a94=(a94+a97);
  a97=(a43*a64);
  a94=(a94+a97);
  a94=(a30*a94);
  a93=(a93+a94);
  a94=(a33*a93);
  a97=(a16*a94);
  a36=(a36*a90);
  a98=(a24*a28);
  a99=(a38*a98);
  a38=(a38*a99);
  a36=(a36-a38);
  a38=(a24*a27);
  a36=(a36+a38);
  a36=(a30*a36);
  a36=(a67+a36);
  a38=(a33*a36);
  a100=(a14*a38);
  a97=(a97+a100);
  a100=(a35*a93);
  a101=(a20*a91);
  a102=(a20*a101);
  a103=(a18*a19);
  a75=(a75+a103);
  a102=(a102-a75);
  a102=(a25*a102);
  a100=(a100+a102);
  a74=(a12*a74);
  a100=(a100+a74);
  a49=(a49*a63);
  a49=(a12*a49);
  a100=(a100+a49);
  a49=(a14*a100);
  a97=(a97+a49);
  a89=(a89-a97);
  a97=(a20*a19);
  a49=(a20*a97);
  a37=(a37+a49);
  a49=(a18*a91);
  a37=(a37+a49);
  a37=(a25*a37);
  a49=(a35*a36);
  a37=(a37+a49);
  a37=(a37+a80);
  a7=(a3*a7);
  a7=(a12*a7);
  a37=(a37+a7);
  a7=(a16*a37);
  a89=(a89+a7);
  a89=(a1*a89);
  a7=(a16*a38);
  a80=(a14*a94);
  a7=(a7-a80);
  a80=(a16*a100);
  a7=(a7+a80);
  a80=(a8*a92);
  a49=(a8*a80);
  a63=(a4*a57);
  a49=(a49-a63);
  a49=(a2*a49);
  a7=(a7+a49);
  a49=(a14*a37);
  a7=(a7+a49);
  a7=(a0*a7);
  a89=(a89-a7);
  if (res[0]!=0) res[0][1]=a89;
  a89=(a43*a41);
  a7=(a8*a89);
  a49=(a8*a7);
  a63=(a24*a34);
  a74=(a4*a63);
  a49=(a49+a74);
  a49=(a2*a49);
  a58=(a30*a58);
  a43=(a43*a64);
  a43=(a30*a43);
  a58=(a58+a43);
  a43=(a33*a58);
  a64=(a16*a43);
  a27=(a24*a27);
  a27=(a30*a27);
  a67=(a67+a27);
  a33=(a33*a67);
  a27=(a14*a33);
  a64=(a64+a27);
  a27=(a35*a58);
  a74=(a20*a63);
  a102=(a20*a74);
  a75=(a18*a89);
  a102=(a102-a75);
  a102=(a25*a102);
  a27=(a27+a102);
  a102=(a14*a27);
  a64=(a64+a102);
  a49=(a49-a64);
  a64=(a20*a89);
  a20=(a20*a64);
  a18=(a18*a63);
  a20=(a20+a18);
  a25=(a25*a20);
  a35=(a35*a67);
  a25=(a25+a35);
  a35=(a16*a25);
  a49=(a49+a35);
  a1=(a1*a49);
  a49=(a16*a33);
  a35=(a14*a43);
  a49=(a49-a35);
  a16=(a16*a27);
  a49=(a49+a16);
  a16=(a8*a63);
  a8=(a8*a16);
  a4=(a4*a89);
  a8=(a8-a4);
  a2=(a2*a8);
  a49=(a49+a2);
  a14=(a14*a25);
  a49=(a49+a14);
  a0=(a0*a49);
  a1=(a1-a0);
  if (res[0]!=0) res[0][2]=a1;
  a23=(a23*a78);
  a87=(a87*a82);
  a83=(a17*a83);
  a87=(a87+a83);
  a23=(a23-a87);
  a79=(a22*a79);
  a23=(a23+a79);
  a52=(a42*a52);
  a69=(a76*a69);
  a70=(a34*a70);
  a69=(a69+a70);
  a52=(a52-a69);
  a61=(a41*a61);
  a52=(a52+a61);
  a23=(a23+a52);
  a61=(a65*a44);
  a23=(a23+a61);
  a66=(a26*a66);
  a23=(a23+a66);
  a66=(a29*a54);
  a23=(a23+a66);
  a73=(a28*a73);
  a23=(a23+a73);
  a73=(a62*a48);
  a73=(a23+a73);
  a50=(a6*a50);
  a73=(a73+a50);
  a50=(a11*a55);
  a73=(a73+a50);
  a84=(a10*a84);
  a73=(a73+a84);
  if (res[0]!=0) res[0][3]=a73;
  a42=(a42*a95);
  a76=(a76*a98);
  a99=(a34*a99);
  a76=(a76+a99);
  a42=(a42-a76);
  a96=(a41*a96);
  a42=(a42+a96);
  a96=(a65*a19);
  a96=(a42+a96);
  a97=(a26*a97);
  a96=(a96+a97);
  a97=(a29*a91);
  a96=(a96+a97);
  a101=(a28*a101);
  a96=(a96+a101);
  a101=(a62*a57);
  a101=(a96+a101);
  a88=(a6*a88);
  a101=(a101+a88);
  a88=(a11*a92);
  a101=(a101+a88);
  a80=(a10*a80);
  a101=(a101+a80);
  if (res[0]!=0) res[0][4]=a101;
  a65=(a65*a89);
  a64=(a26*a64);
  a65=(a65+a64);
  a29=(a29*a63);
  a65=(a65+a29);
  a74=(a28*a74);
  a65=(a65+a74);
  a62=(a62*a89);
  a62=(a65+a62);
  a7=(a6*a7);
  a62=(a62+a7);
  a11=(a11*a63);
  a62=(a62+a11);
  a16=(a10*a16);
  a62=(a62+a16);
  if (res[0]!=0) res[0][5]=a62;
  a62=cos(a13);
  a16=(a9*a77);
  a11=(a9*a60);
  a7=(a5*a71);
  a11=(a11+a7);
  a7=(a5*a72);
  a11=(a11+a7);
  a16=(a16-a11);
  a16=(a62*a16);
  a13=sin(a13);
  a71=(a9*a71);
  a60=(a5*a60);
  a71=(a71-a60);
  a72=(a9*a72);
  a71=(a71+a72);
  a77=(a5*a77);
  a71=(a71+a77);
  a71=(a13*a71);
  a16=(a16-a71);
  if (res[0]!=0) res[0][6]=a16;
  a16=(a9*a37);
  a71=(a9*a94);
  a77=(a5*a38);
  a71=(a71+a77);
  a77=(a5*a100);
  a71=(a71+a77);
  a16=(a16-a71);
  a16=(a62*a16);
  a38=(a9*a38);
  a94=(a5*a94);
  a38=(a38-a94);
  a100=(a9*a100);
  a38=(a38+a100);
  a37=(a5*a37);
  a38=(a38+a37);
  a38=(a13*a38);
  a16=(a16-a38);
  if (res[0]!=0) res[0][7]=a16;
  a16=(a9*a25);
  a38=(a9*a43);
  a37=(a5*a33);
  a38=(a38+a37);
  a37=(a5*a27);
  a38=(a38+a37);
  a16=(a16-a38);
  a62=(a62*a16);
  a33=(a9*a33);
  a43=(a5*a43);
  a33=(a33-a43);
  a27=(a9*a27);
  a33=(a33+a27);
  a5=(a5*a25);
  a33=(a33+a5);
  a13=(a13*a33);
  a62=(a62-a13);
  if (res[0]!=0) res[0][8]=a62;
  if (res[0]!=0) res[0][9]=a23;
  if (res[0]!=0) res[0][10]=a96;
  if (res[0]!=0) res[0][11]=a65;
  a65=cos(a32);
  a96=(a31*a68);
  a23=(a40*a59);
  a96=(a96-a23);
  a96=(a65*a96);
  a32=sin(a32);
  a59=(a21*a59);
  a68=(a15*a68);
  a59=(a59+a68);
  a59=(a32*a59);
  a96=(a96-a59);
  if (res[0]!=0) res[0][12]=a96;
  a96=(a31*a36);
  a59=(a40*a93);
  a96=(a96-a59);
  a96=(a65*a96);
  a93=(a21*a93);
  a36=(a15*a36);
  a93=(a93+a36);
  a93=(a32*a93);
  a96=(a96-a93);
  if (res[0]!=0) res[0][13]=a96;
  a31=(a31*a67);
  a40=(a40*a58);
  a31=(a31-a40);
  a65=(a65*a31);
  a58=(a21*a58);
  a15=(a15*a67);
  a58=(a58+a15);
  a32=(a32*a58);
  a65=(a65-a32);
  if (res[0]!=0) res[0][14]=a65;
  if (res[0]!=0) res[0][15]=a52;
  if (res[0]!=0) res[0][16]=a42;
  a55=(a6*a55);
  a48=(a10*a48);
  a55=(a55-a48);
  a22=(a22*a47);
  a17=(a17*a51);
  a22=(a22+a17);
  a44=(a28*a44);
  a22=(a22-a44);
  a54=(a26*a54);
  a22=(a22+a54);
  a46=(a41*a46);
  a53=(a34*a53);
  a46=(a46+a53);
  a53=1.0500000000000000e+001;
  a46=(a46+a53);
  a22=(a22+a46);
  a54=9.0283499999999997e+000;
  a22=(a22+a54);
  a55=(a55+a22);
  a44=9.2650000000000006e+000;
  a55=(a55+a44);
  if (res[0]!=0) res[0][17]=a55;
  a92=(a6*a92);
  a57=(a10*a57);
  a92=(a92-a57);
  a91=(a26*a91);
  a19=(a28*a19);
  a91=(a91-a19);
  a41=(a41*a81);
  a34=(a34*a90);
  a41=(a41+a34);
  a41=(a41+a53);
  a91=(a91+a41);
  a91=(a91+a54);
  a92=(a92+a91);
  if (res[0]!=0) res[0][18]=a92;
  a6=(a6*a63);
  a92=(a10*a89);
  a6=(a6-a92);
  a26=(a26*a63);
  a89=(a28*a89);
  a26=(a26-a89);
  a26=(a26+a53);
  a6=(a6+a26);
  if (res[0]!=0) res[0][19]=a6;
  if (res[0]!=0) res[0][20]=a22;
  if (res[0]!=0) res[0][21]=a91;
  if (res[0]!=0) res[0][22]=a26;
  if (res[0]!=0) res[0][23]=a46;
  if (res[0]!=0) res[0][24]=a41;
  if (res[0]!=0) res[0][25]=a53;
  a30=(a30*a39);
  a45=(a45+a30);
  a45=(a24*a45);
  a12=(a12*a21);
  a10=(a10+a12);
  a10=(a3*a10);
  a45=(a45+a10);
  a85=(a85*a9);
  a86=(a86*a85);
  a45=(a45+a86);
  a45=(a56*a45);
  if (res[0]!=0) res[0][26]=a45;
  a28=(a28+a30);
  a28=(a24*a28);
  a3=(a3*a12);
  a28=(a28+a3);
  a28=(a56*a28);
  if (res[0]!=0) res[0][27]=a28;
  a24=(a24*a30);
  a56=(a56*a24);
  if (res[0]!=0) res[0][28]=a56;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void jac_F_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_F_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_F_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int jac_F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* jac_F_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "out_o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_F_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_F_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_F_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
